### PR TITLE
patch TF-M 2.0 to work with MbedTLS 3.6.0

### PR DESCRIPTION
**Pull request by tomi-font**
Patches provided by @adeaarm in https://review.trustedfirmware.org/c/TF-M/tf-m-tests/+/27720.

### CODE REVIEW

**Review by frkv — APPROVED** [review]
LGTM

**Review by mswarowsky — APPROVED** [review]
lgtm

**Review by d3zd3z — APPROVED** [review]

**Comment by tomi-font** [comment]
Can this be merged? @d3zd3z @carlescufi

**Comment by adeaarm** [comment]
LGTM

**Review by ithinuel — APPROVED** [review]

**Pull request merged**
